// The commit message field, its "Generate with AI" action, and the
// Commit button — the tail end of the stage → review → commit flow.
// Adapted from the standalone CommitBox to require staged changes: with
// nothing staged there is nothing meaningful to summarise or commit, so
// both actions stay disabled and say why.
import { useState } from "react";
import { generateCommitMessage, aiConfigured, getAISettings } from "../../ai";
import { track } from "../../analytics";

export default function CommitPanel({ projectRoot, stagedCount, busy, onCommit }) {
  const [msg, setMsg] = useState("");
  const [generating, setGenerating] = useState(false);
  const [hint, setHint] = useState(null);
  // Text that came from the model, so a later edit can be told apart
  // from an as-is accept when the commit is reported.
  const [suggested, setSuggested] = useState(null);
  const { model } = getAISettings();

  const edit = (text) => {
    setMsg(text);
    setHint(null);
  };

  const generate = async () => {
    if (generating || busy || stagedCount === 0) return;
    if (!aiConfigured()) {
      setHint({ kind: "err", text: "Pick a local model in Preferences → AI first." });
      return;
    }
    setGenerating(true);
    setHint(null);
    try {
      const r = await generateCommitMessage(projectRoot);
      setMsg(r.message || "");
      setSuggested(r.message || "");
      setHint({
        kind: "ok",
        text:
          `Summarised ${r.fileCount} staged file${r.fileCount === 1 ? "" : "s"}` +
          (r.truncated ? " · diff was large, so only part of it was read" : ""),
      });
    } catch (e) {
      setHint({ kind: "err", text: String(e) });
    } finally {
      setGenerating(false);
    }
  };

  const commit = async () => {
    const text = msg.trim();
    if (!text || stagedCount === 0) return;
    if (suggested) {
      track("ai_suggestion_accepted", {
        surface: "commit_message",
        edited: text !== suggested.trim(),
        message_length: text.length,
      });
    }
    const hash = await onCommit(text);
    if (hash) {
      setMsg("");
      setSuggested(null);
      setHint(null);
    }
  };

  return (
    <div className="git-commit-panel">
      <div className="git-commit-panel-head">
        <span className="git-panel-title">Commit message</span>
        {suggested && suggested === msg && (
          <span className="git-commit-generated-by">Generated by {model || "local model"}</span>
        )}
      </div>
      <textarea
        className="git-commit-msg"
        rows={msg.includes("\n") ? 5 : 3}
        placeholder={stagedCount === 0 ? "Stage changes to write a commit message" : "Commit message"}
        value={msg}
        disabled={stagedCount === 0}
        onChange={(e) => edit(e.target.value)}
        // Enter inserts a newline (commit bodies are multi-line);
        // Cmd/Ctrl+Enter commits, matching every other commit editor.
        onKeyDown={(e) => {
          if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
            e.preventDefault();
            commit();
          }
        }}
      />
      <div className="git-commit-actions">
        <button
          type="button"
          className="btn small ai"
          disabled={busy || generating || stagedCount === 0}
          onClick={generate}
          title="Draft a commit message from your staged changes"
        >
          {generating ? "Generating…" : suggested ? "↻ Regenerate" : "✨ Generate Commit Message"}
        </button>
        <button
          type="button"
          className="btn primary git-commit-submit"
          disabled={busy || generating || !msg.trim() || stagedCount === 0}
          onClick={commit}
        >
          Commit Changes
        </button>
      </div>
      {hint && <p className={`detect-note ${hint.kind}`}>{hint.text}</p>}
    </div>
  );
}
