// Single import point for Wails bindings.
// The wailsjs folder is generated by `wails dev` / `wails build`.
//
// Action methods that we want in analytics are wrapped below to fire a
// GA/Clarity event as a side effect; everything else is re-exported as-is.
import * as App from "../wailsjs/go/main/App";
import { track } from "./analytics";

// --- Pass-through bindings (no analytics) ---
export const {
  GetProjects,
  GetStatus,
  GetLogs,
  PickDirectory,
  DetectProcesses,
  ReadEnvFile,
  GetDependencies,
  GetUsage,
  GetPortMap,
  UpdateTasks,
  UpdateSprints,
  ReadConfigFile,
  PickConfigFile,
  GetImportPath,
  SetNativeTheme,
  OllamaListModels,
  OllamaEnrichTask,
  OllamaChat,
  GitStatus,
  GitInit,
  GitFetch,
  GitPull,
  GitAddRemote,
  GitListBranches,
  GitGraphLog,
  GitCheckout,
  GitCreateBranch,
  GitDeleteBranch,
  GitDiff,
  GitListStashes,
  HasGitToken,
  DeleteGitToken,
  GenerateProjectDescription,
  DetectTestConfig,
  DetectScripts,
  StopScriptRun,
  ListScriptRuns,
  ListProcessScriptRuns,
  GetScriptRunStatus,
  DockerInfo,
  ListContainers,
  ListImages,
  ListVolumes,
  StartContainer,
  StopContainer,
  RemoveContainer,
  CheckForUpdate,
  InstallUpdate,
  RestartApp,
  GetAppVersion,
  GetRemoteBanner,
} = App;

export {
  EventsOn,
  EventsOff,
  BrowserOpenURL,
  ClipboardSetText,
} from "../wailsjs/runtime/runtime";

// --- Wrapped bindings (fire analytics, then delegate) ---

// Process control
export function StartProcess(...a) {
  track("process_start");
  return App.StartProcess(...a);
}
export function StopProcess(...a) {
  track("process_stop");
  return App.StopProcess(...a);
}
export function StartAll(...a) {
  track("process_start_all");
  return App.StartAll(...a);
}
export function StopAll(...a) {
  track("process_stop_all");
  return App.StopAll(...a);
}

// Scripts & tests
export function RunScript(...a) {
  track("script_run");
  return App.RunScript(...a);
}
export function RunTests(...a) {
  track("tests_run");
  return App.RunTests(...a);
}

// Dependencies
export function InstallDeps(...a) {
  track("deps_install");
  return App.InstallDeps(...a);
}

// Projects & import
export function SaveProject(...a) {
  track("project_saved");
  return App.SaveProject(...a);
}
export function DeleteProject(...a) {
  track("project_deleted");
  return App.DeleteProject(...a);
}
export function ImportConfig(...a) {
  track("config_imported", { source: "path" });
  return App.ImportConfig(...a);
}
export function ImportConfigText(...a) {
  track("config_imported", { source: "text" });
  return App.ImportConfigText(...a);
}
export function ImportConfigFile(...a) {
  track("config_imported", { source: "file" });
  return App.ImportConfigFile(...a);
}

// Git & releases
export function SaveGitToken(...a) {
  track("git_connected");
  return App.SaveGitToken(...a);
}
export function GitCommit(...a) {
  track("git_commit");
  return App.GitCommit(...a);
}
export function GitPush(...a) {
  track("git_push");
  return App.GitPush(...a);
}
export function CreateRelease(...a) {
  track("release_created");
  return App.CreateRelease(...a);
}

// Docker
export function ComposeUp(...a) {
  track("compose_up");
  return App.ComposeUp(...a);
}
export function ComposeDown(...a) {
  track("compose_down");
  return App.ComposeDown(...a);
}
