// Single import point for Wails bindings.
// The wailsjs folder is generated by `wails dev` / `wails build`.
export {
  GetProjects,
  SaveProject,
  DeleteProject,
  StartProcess,
  StopProcess,
  StartAll,
  StopAll,
  GetStatus,
  GetLogs,
  PickDirectory,
  DetectProcesses,
  ReadEnvFile,
  GetDependencies,
  InstallDeps,
  GetUsage,
  GetPortMap,
  UpdateTasks,
  ImportConfig,
  GetImportPath,
  SetNativeTheme,
} from "../wailsjs/go/main/App";

export {
  EventsOn,
  EventsOff,
  BrowserOpenURL,
  ClipboardSetText,
} from "../wailsjs/runtime/runtime";
